# Uses VS Code 'REST Client' extension. More info: https://github.com/Huachao/vscode-restclient
@hostname = 127.0.0.1
@port = 5000
@host = {{hostname}}:{{port}}

###

GET http://{{host}}/ HTTP/1.1
Content-Type: application/json

###

POST http://{{host}}/api/room HTTP/1.1
Content-Type: application/json

{
    "name": "room1"
}

###

POST http://{{host}}/api/temperature HTTP/1.1
Content-Type: application/json

{
    "room": "1",
    "temperature": "23"
}

###

GET http://{{host}}/api/average HTTP/1.1
Content-Type: application/json

###

GET http://{{host}}/api/room/1 HTTP/1.1
Content-Type: application/json

###

GET http://{{host}}/api/room/1?term=week HTTP/1.1
Content-Type: application/json

###

GET http://{{host}}/api/room/1?term=month HTTP/1.1
Content-Type: application/json

###